#!/bin/sh
# invoke insmod with all arguments we were passed
# and use a pathname, as newer modutils dont look in . by default

echo " "
echo " "
#install omap_notify driver
echo "installing /binaries/omap_notify.ko"
insmod /binaries/omap_notify.ko

#install notify syslink proc driver
echo "installing notify_tesladriver.ko"
insmod /binaries/notify_tesladriver.ko

#install notify syslink proc4430 driver
echo "installing dspbridge.ko"
insmod /binaries/dspbridge.ko

#install notify tesla driver
echo "installing bridgedriver.ko"
insmod bridgedriver.ko


# Updated for BusyBox since it doesn't have awk - used sed instead
MAJ=`cat /proc/devices | sed -ne "/DspBridge/s/DspBridge.*$//p"`
if [ -z "$MAJ" ]
then
    echo "Can't find DspBridge driver, can't continue"
        exit 1
fi
CNT=`echo "$MAJ" | wc -l`
if [ $CNT != 1 ]
then
    echo "Found multiple instances of DspBridge driver, can't continue"
    exit 1
fi

echo "calling mknod... DspBridge"
mknod /dev/DspBridge c $MAJ 0

